# Generated by Django 5.2 on 2025-12-22 11:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceBookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Price Book Categories',
                'ordering': ['vertical', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Vertical',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('calculation_unit', models.CharField(choices=[('project', 'Project-Based'), ('square', 'Per Square (100 sqft)'), ('watt', 'Per Watt'), ('opening', 'Per Opening'), ('unit', 'Per Unit')], default='project', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Verticals',
            },
        ),
        migrations.CreateModel(
            name='ContractorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('overhead_percent', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('profit_margin_percent', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=5)),
                ('default_labor_rate', models.DecimalField(decimal_places=2, default=Decimal('75.00'), max_digits=6)),
                ('tax_rate', models.DecimalField(decimal_places=3, default=Decimal('8.250'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PriceBookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('price_multiplier', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=5)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_type', models.CharField(blank=True, max_length=20)),
                ('prompt_hint', models.CharField(blank=True, max_length=200)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricing.pricebookcategory')),
            ],
            options={
                'ordering': ['category', 'sort_order'],
                'unique_together': {('category', 'item_id')},
            },
        ),
        migrations.CreateModel(
            name='PriceCalculationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertical', models.CharField(max_length=50)),
                ('input_config', models.JSONField(default=dict)),
                ('cost_breakdown', models.JSONField(default=dict)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calculation_type', models.CharField(default='estimate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.contractorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pricebookcategory',
            name='vertical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='pricing.vertical'),
        ),
        migrations.CreateModel(
            name='ContractorPriceOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_adjustment_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('effective_date', models.DateField(auto_now_add=True)),
                ('expires_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='pricing.contractorprofile')),
                ('price_book_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.pricebookitem')),
            ],
            options={
                'unique_together': {('contractor', 'price_book_item')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='pricebookcategory',
            unique_together={('vertical', 'slug')},
        ),
    ]
