# Generated by Django 5.2 on 2025-05-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_generatedimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizationrequest',
            name='progress_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Processing progress percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='visualizationrequest',
            name='status_message',
            field=models.CharField(blank=True, help_text='Current processing status message', max_length=200),
        ),
    ]
