# Generated by Django 5.2 on 2025-11-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_visualizationrequest_progress_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screentype',
            name='name',
            field=models.CharField(help_text='Screen type name (e.g., Security, Lifestyle)', max_length=100, unique=True),
        ),
    ]
