# Generated by Django 5.2 on 2025-11-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_screentype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizationrequest',
            name='color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Dark Bronze', 'Dark Bronze'), ('Stucco', 'Stucco')], help_text='Screen frame/fabric color', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visualizationrequest',
            name='opacity',
            field=models.CharField(blank=True, choices=[('80', '80%'), ('95', '95%'), ('99', '99%')], help_text='Screen opacity percentage', max_length=10, null=True),
        ),
    ]
