# Generated by Django 5.2 on 2025-11-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_visualizationrequest_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata (e.g., quality score, generation params)'),
        ),
    ]
