# Generated by Django 5.2 on 2025-11-26 17:42

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_generatedimage_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizationrequest',
            name='clean_image',
            field=models.ImageField(blank=True, help_text='Intermediate cleaned image (Step 1)', null=True, upload_to=api.models.upload_to_generated),
        ),
    ]
