# Generated by Django 5.2 on 2025-11-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_visualizationrequest_clean_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualizationrequest',
            name='screen_type',
            field=models.CharField(choices=[('window_fixed', 'Fixed Security Window (Surface Mount)'), ('door_single', 'Hinged Security Door (Single)'), ('door_sliding', 'Sliding Security Door (Heavy Duty)'), ('door_french', 'French Security Doors (Double)'), ('door_accordion', 'Accordion/Bi-Fold Security Door (Stacking)'), ('patio_enclosure', 'Patio Enclosure / Stand Alone')], default='window_fixed', help_text='Type of screen to overlay', max_length=50),
        ),
        migrations.DeleteModel(
            name='ScreenType',
        ),
    ]
