# Generated by Django 5.2 on 2025-11-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_visualizationrequest_screen_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizationrequest',
            name='mesh_type',
            field=models.CharField(choices=[('10x10', '10x10 Heavy Duty'), ('12x12', '12x12 Standard'), ('12x12_american', '12x12 American Standard')], default='12x12', help_text='Type of mesh to use for the screen', max_length=20),
        ),
        migrations.AlterField(
            model_name='visualizationrequest',
            name='screen_type',
            field=models.CharField(choices=[('window_fixed', 'Fixed Security Window (Surface Mount)'), ('door_single', 'Hinged Security Door (Single)'), ('door_sliding', 'Sliding Security Door (Heavy Duty)'), ('door_french', 'French Security Doors (Double)'), ('door_accordion', 'Accordion/Bi-Fold Security Door (Stacking)'), ('patio_enclosure', 'Patio Enclosure / Stand Alone')], default='window_fixed', help_text='Type of screen to overlay', max_length=20),
        ),
    ]
