# Generated by Django 5.2 on 2025-11-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_visualizationrequest_mesh_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizationrequest',
            name='frame_color',
            field=models.CharField(choices=[('Black', 'Black'), ('Dark Bronze', 'Dark Bronze'), ('Stucco', 'Stucco'), ('White', 'White'), ('Almond', 'Almond')], default='Black', help_text='Selected frame color', max_length=20),
        ),
        migrations.AddField(
            model_name='visualizationrequest',
            name='mesh_choice',
            field=models.CharField(choices=[('10x10', '10x10 Standard'), ('12x12', '12x12 Standard'), ('12x12_american', '12x12 American')], default='12x12', help_text='Selected mesh type', max_length=20),
        ),
        migrations.AddField(
            model_name='visualizationrequest',
            name='mesh_color',
            field=models.CharField(choices=[('Black', 'Black (Recommended)'), ('Stucco', 'Stucco'), ('Bronze', 'Bronze')], default='Black', help_text='Selected mesh color', max_length=20),
        ),
        migrations.AddField(
            model_name='visualizationrequest',
            name='screen_categories',
            field=models.JSONField(default=list, help_text='Selected screen categories (Window, Door, Patio)'),
        ),
        migrations.AlterField(
            model_name='visualizationrequest',
            name='color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Dark Bronze', 'Dark Bronze'), ('Stucco', 'Stucco')], help_text='Legacy: Screen frame/fabric color', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visualizationrequest',
            name='mesh_type',
            field=models.CharField(choices=[('10x10', '10x10 Heavy Duty'), ('12x12', '12x12 Standard'), ('12x12_american', '12x12 American Standard')], default='12x12', help_text='Legacy: Type of mesh to use', max_length=20),
        ),
        migrations.AlterField(
            model_name='visualizationrequest',
            name='opacity',
            field=models.CharField(blank=True, choices=[('80', '80%'), ('95', '95%'), ('99', '99%')], help_text='Legacy: Screen opacity percentage', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='visualizationrequest',
            name='screen_type',
            field=models.CharField(choices=[('window_fixed', 'Fixed Security Window (Surface Mount)'), ('door_single', 'Hinged Security Door (Single)'), ('door_sliding', 'Sliding Security Door (Heavy Duty)'), ('door_french', 'French Security Doors (Double)'), ('door_accordion', 'Accordion/Bi-Fold Security Door (Stacking)'), ('patio_enclosure', 'Patio Enclosure / Stand Alone')], default='window_fixed', help_text='Legacy: Type of screen to overlay', max_length=20),
        ),
    ]
