# Generated by Django 5.2 on 2025-11-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_visualizationrequest_frame_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizationrequest',
            name='scope',
            field=models.JSONField(blank=True, default=dict, help_text='Sales scope (hasPatio, hasWindows, hasDoors, doorType)'),
        ),
    ]
