# Generated by Django 5.2 on 2025-11-28 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_scope_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_ground_level_access', models.BooleanField(default=False, help_text='Windows within 6ft of ground')),
                ('has_concealment', models.BooleanField(default=False, help_text='Windows hidden by landscaping')),
                ('has_glass_proximity', models.BooleanField(default=False, help_text='Glass within 40 inches of door lock')),
                ('has_hardware_weakness', models.BooleanField(default=False, help_text='Visible standard fly screens')),
                ('vulnerabilities', models.JSONField(default=list, help_text='List of detected vulnerabilities with coordinates and descriptions')),
                ('analysis_summary', models.TextField(help_text='AI generated summary of security risks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(help_text='Associated visualization request', on_delete=django.db.models.deletion.CASCADE, related_name='audit_report', to='api.visualizationrequest')),
            ],
        ),
    ]
