# Generated by Django 5.2 on 2025-12-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auditreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizationrequest',
            name='door_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of doors to screen'),
        ),
        migrations.AddField(
            model_name='visualizationrequest',
            name='door_type',
            field=models.CharField(blank=True, choices=[('single', 'Single Entry Door'), ('french', 'French Doors'), ('sliding', 'Sliding Patio Door')], help_text='Type of security door', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visualizationrequest',
            name='patio_enclosure',
            field=models.BooleanField(default=False, help_text='Include patio enclosure'),
        ),
        migrations.AddField(
            model_name='visualizationrequest',
            name='window_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of windows to screen'),
        ),
        migrations.AlterField(
            model_name='visualizationrequest',
            name='color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Dark Bronze', 'Dark Bronze'), ('Stucco', 'Stucco'), ('White', 'White'), ('Almond', 'Almond')], help_text='Legacy: Screen frame/fabric color', max_length=50, null=True),
        ),
    ]
