# Generated by Django 5.2 on 2025-12-02 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_opening_count_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizationrequest',
            name='generated_pdf',
            field=models.FileField(blank=True, help_text='Pre-generated PDF quote/audit report', null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='visualizationrequest',
            name='door_type',
            field=models.CharField(blank=True, choices=[('security_door', 'Single Entry Door'), ('french_door', 'French Doors'), ('sliding_door', 'Sliding Patio Door')], help_text='Type of security door', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer full name', max_length=200)),
                ('email', models.EmailField(help_text='Customer email address', max_length=254)),
                ('phone', models.CharField(help_text='Customer phone number', max_length=20)),
                ('address_street', models.CharField(help_text='Street address', max_length=200)),
                ('address_city', models.CharField(help_text='City', max_length=100)),
                ('address_state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('DC', 'District of Columbia')], help_text='State', max_length=2)),
                ('address_zip', models.CharField(help_text='ZIP code', max_length=20)),
                ('is_existing_customer', models.BooleanField(default=False, help_text='If true, skip Monday.com push (sales rep marked as existing)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visualization', models.ForeignKey(help_text='Associated visualization request', on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='api.visualizationrequest')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
