# Generated by Django 5.2 on 2025-12-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_lead_and_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditreport',
            name='assessment_summary',
            field=models.TextField(default='', help_text='AI generated summary of site readiness'),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='has_access_considerations',
            field=models.BooleanField(default=False, help_text='Equipment access challenges'),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='has_grading_needed',
            field=models.BooleanField(default=False, help_text='Slope or terrain issues'),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='has_structure_relocation_needed',
            field=models.BooleanField(default=False, help_text='Structures to move/remove'),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='has_tree_clearance_needed',
            field=models.BooleanField(default=False, help_text='Large trees in pool zone'),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='site_items',
            field=models.JSONField(default=list, help_text='List of site items identified with descriptions and actions'),
        ),
        migrations.AlterField(
            model_name='auditreport',
            name='analysis_summary',
            field=models.TextField(default='', help_text='DEPRECATED - use assessment_summary'),
        ),
        migrations.AlterField(
            model_name='auditreport',
            name='has_concealment',
            field=models.BooleanField(default=False, help_text='DEPRECATED - use has_structure_relocation_needed'),
        ),
        migrations.AlterField(
            model_name='auditreport',
            name='has_glass_proximity',
            field=models.BooleanField(default=False, help_text='DEPRECATED - use has_grading_needed'),
        ),
        migrations.AlterField(
            model_name='auditreport',
            name='has_ground_level_access',
            field=models.BooleanField(default=False, help_text='DEPRECATED - use has_tree_clearance_needed'),
        ),
        migrations.AlterField(
            model_name='auditreport',
            name='has_hardware_weakness',
            field=models.BooleanField(default=False, help_text='DEPRECATED - use has_access_considerations'),
        ),
        migrations.AlterField(
            model_name='auditreport',
            name='vulnerabilities',
            field=models.JSONField(default=list, help_text='DEPRECATED - use site_items'),
        ),
    ]
