# Generated by Django 5.2.9 on 2025-12-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_pool_site_assessment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizationrequest',
            name='tenant_id',
            field=models.CharField(default='pools', help_text='Tenant identifier (pools, windows, roofs)', max_length=50),
        ),
    ]
