# Generated by Django 5.2 on 2025-12-22 12:01

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_tenant_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, help_text="Unique tenant identifier (e.g., 'screens', 'pools')", max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable tenant name', max_length=100)),
                ('product_categories', models.JSONField(default=list, help_text='Product category definitions for dynamic forms')),
                ('pipeline_steps', models.JSONField(default=list, help_text='Ordered list of pipeline step names')),
                ('step_configs', models.JSONField(default=dict, help_text='Configuration for each pipeline step')),
                ('branding', models.JSONField(default=dict, help_text='Branding config (colors, logo path)')),
                ('config_version', models.PositiveIntegerField(default=1, help_text='Version number, incremented on sync')),
                ('synced_from_yaml_at', models.DateTimeField(auto_now=True, help_text='When config was last synced from YAML')),
            ],
            options={
                'verbose_name': 'Tenant Config',
                'verbose_name_plural': 'Tenant Configs',
            },
        ),
        migrations.CreateModel(
            name='PromptOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, help_text='Tenant this override applies to', max_length=50)),
                ('step_name', models.CharField(help_text="Pipeline step name (e.g., 'cleanup', 'doors', 'quality_check')", max_length=50)),
                ('prompt_text', models.TextField(help_text='Override prompt text (supports {variable} substitution)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this override is active')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for this override')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this override', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prompt Override',
                'verbose_name_plural': 'Prompt Overrides',
                'ordering': ['-version'],
                'unique_together': {('tenant_id', 'step_name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, help_text='Tenant this image belongs to', max_length=50)),
                ('category', models.CharField(help_text="Product category key (e.g., 'mesh_type', 'pool_shape')", max_length=50)),
                ('option_value', models.CharField(help_text="Option value this image represents (e.g., 'black', 'rectangle')", max_length=50)),
                ('image', models.ImageField(help_text='Full-size reference image', upload_to=api.models.upload_to_reference_images)),
                ('thumbnail', models.ImageField(blank=True, help_text='Auto-generated thumbnail', null=True, upload_to=api.models.upload_to_reference_thumbnails)),
                ('description', models.CharField(blank=True, help_text='Optional description of this reference image', max_length=200)),
                ('embedding', models.JSONField(blank=True, help_text='AI embedding vector for similarity matching (future use)', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded this image', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reference Image',
                'verbose_name_plural': 'Reference Images',
                'ordering': ['tenant_id', 'category', 'option_value'],
                'unique_together': {('tenant_id', 'category', 'option_value')},
            },
        ),
    ]
