# Generated by Django 5.2 on 2025-12-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_tenantconfig_promptoverride_referenceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizationrequest',
            name='price_data',
            field=models.JSONField(blank=True, help_text='Calculated price breakdown from pricing engine', null=True),
        ),
    ]
