# Generated by Django 6.0 on 2025-12-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_visualizationrequest_price_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizationrequest',
            name='contractor_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID of matched contractor from contractors_contractor table (if FEATURE_CONTRACTOR_LINKING enabled)', null=True),
        ),
    ]
