# Generated by Django 6.0 on 2025-12-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_contractor_linking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualizationrequest',
            name='status_message',
            field=models.CharField(blank=True, help_text='Current processing status message', max_length=500),
        ),
    ]
