# Generated by Django 6.0.1 on 2026-01-12 07:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0020_increase_status_message_length'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(help_text='Stripe Customer ID', max_length=255)),
                ('stripe_subscription_id', models.CharField(help_text='Stripe Subscription ID', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete')], default='incomplete', max_length=20)),
                ('current_period_end', models.DateTimeField(help_text='When current billing period ends')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('contractor', models.OneToOneField(help_text='Contractor with this subscription', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='pricing.contractorprofile')),
            ],
            options={
                'verbose_name': 'Contractor Subscription',
                'verbose_name_plural': 'Contractor Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeownerDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_checkout_session_id', models.CharField(help_text='Stripe Checkout Session ID', max_length=255, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Stripe Payment Intent ID (set after payment)', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Deposit amount in dollars', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('credited', 'Credited to Invoice')], default='pending', max_length=20)),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('credited_to_contractor', models.ForeignKey(blank=True, help_text='Contractor this deposit was credited to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.contractorprofile')),
                ('lead', models.OneToOneField(help_text='Lead who made this deposit', on_delete=django.db.models.deletion.PROTECT, related_name='deposit', to='api.lead')),
                ('visualization', models.ForeignKey(help_text='Visualization this deposit is for', on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='api.visualizationrequest')),
            ],
            options={
                'verbose_name': 'Homeowner Deposit',
                'verbose_name_plural': 'Homeowner Deposits',
                'ordering': ['-created_at'],
            },
        ),
    ]
